# Generated by Django 5.0.7 on 2025-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_producto', models.CharField(choices=[('herramienta', 'Herramienta'), ('material', 'Material'), ('electrico', 'Eléctrico'), ('pintura', 'Pintura')], default='herramienta', max_length=20)),
                ('marca', models.CharField(choices=[('bosch', 'Bosch'), ('stanley', 'Stanley'), ('dewalt', 'DeWalt'), ('makita', 'Makita')], default='bosch', max_length=20)),
                ('precio', models.IntegerField()),
                ('producto_popular', models.BooleanField(default=False)),
                ('foto', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
